### PR TITLE
Backported maia 4.0.0 to rails 4.2

### PR DESCRIPTION
**Pull request by twohlix**
As discussed in Issue #4 here's the changes required to get this gem's master branch working with Rails4 as of Feb 6th, 2018.

### CODE REVIEW

**Comment by twohlix** [comment]
Whoops. This is targeting the wrong branch. ugh.

**Comment by twohlix** [comment]
Addressed and now pointing at the right branch.

**Comment by lserman** [comment]
Could you just change the "master" in .travis.yml to be "rails4-x" so that the gem gets released automatically from this branch?

**Comment by twohlix** [comment]
Done

**Pull request merged**
